// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckyvmlisbginwbmmrhdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNreXZtbGlzYmdpbndibW1yaGRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NTIyMTQsImV4cCI6MjA3MzEyODIxNH0.19T8oZgQ822JsoCFnLcf88GUV1rS_j9Axd3sxAKe0kM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});